Acp 104 server log
adshares/adserver pull request #1250
Opened 2022-10-14 07:39 UTC by PawelPodkalicki

2022-10-24 14:11 UTC, m-pilarczyk requested changes

2022-10-24 14:11 UTC, m-pilarczyk commented on app/Console/Commands/AdsFetchHosts.php
> +        ServerEvent::dispatch(ServerEventType::HostBroadcastProcessed, ['marked' => $marked, 'removed' => $removed]);
Add registered hosts counter

2022-10-25 06:30 UTC, PawelPodkalicki commented on app/Console/Commands/AdsFetchHosts.php
> +        ServerEvent::dispatch(ServerEventType::HostBroadcastProcessed, ['marked' => $marked, 'removed' => $removed]);
Added

2022-10-25 09:59 UTC, m-pilarczyk requested changes

2022-10-25 09:59 UTC, m-pilarczyk commented on app/Console/Commands/AdsFetchHosts.php
> +                if ($wasHostFound) {
```suggestion
                if ($this->handleBroadcast($broadcast)) {
```

2022-10-25 09:59 UTC, m-pilarczyk commented on app/Console/Commands/AdsFetchHosts.php
> +                $wasHostFound = $this->handleBroadcast($broadcast);
```suggestion
```

2022-10-25 10:17 UTC, m-pilarczyk approved these changes

2022-10-25 10:17 UTC, merged