[wip] Add zone scopes
adshares/adserver pull request #1278
Opened 2022-12-16 10:55 UTC by PawelPodkalicki

2022-12-16 13:27 UTC, PawelPodkalicki commented on app/Services/Publisher/SiteCodeGenerator.php
> -
This function was not used.

2022-12-16 13:31 UTC, PawelPodkalicki commented on src/Supply/Domain/ValueObject/Size.php
> -
This function was not used.

2022-12-19 09:38 UTC, m-pilarczyk requested changes

2022-12-19 09:38 UTC, m-pilarczyk commented on database/migrations/2019_11_13_161923_change_width_and_height_into_size.php
> +                $table->string('type')->default(Zone::TYPE_DISPLAY)->change();
remove consts from migrations

2022-12-19 10:21 UTC, m-pilarczyk approved these changes

2022-12-19 10:38 UTC, merged