opportunity to change favicon
adshares/adserver pull request #1389
Opened 2023-05-10 12:29 UTC by Niko-Yea

2023-05-10 12:41 UTC, PawelPodkalicki requested changes

2023-05-10 12:41 UTC, PawelPodkalicki commented on deploy/build.sh
> +reload.sh
deploy/reload.sh

2023-05-10 12:41 UTC, PawelPodkalicki commented on deploy/reload.sh
> +    NEW_FAVICON=$(find ${BRAND_ASSETS_DIR} -type f -name "favicon-*" | sort -t '\0' -n | tail -1)
check sort options

2023-05-10 13:10 UTC, PawelPodkalicki approved these changes

2023-05-10 13:10 UTC, PawelPodkalicki approved these changes

2023-05-12 14:02 UTC, m-pilarczyk approved these changes

2023-05-12 14:02 UTC, merged