Travis improvements
adshares/adserver pull request #178
Opened 2018-11-14 15:03 UTC by awlodarkiewicz

New test time:  1 min 55 sec

2018-11-14 15:29 UTC, c3zi submitted a review, later dismissed

2018-11-14 15:29 UTC, c3zi commented on .travis.yml
> +    if: type = pull_request
It should be run only when we want to merge into master. Shouldn't it?

```if: type = pull_request AND branch=master```

2018-11-14 15:29 UTC, c3zi commented on .travis.yml
> +    if: type = pull_request
Code quality stage should be run for every commit ...

2018-11-15 12:11 UTC, teghnet requested changes

2018-11-15 12:11 UTC, pawzar commented on .travis.yml
> +    - DOCKER_IMAGE=awlodarkiewicz/devops:adserver
What is wrong with `adshares/adserver:devops`?
We can create `adshares/devops:adserver`.

2018-11-15 12:11 UTC, pawzar commented on .travis.yml
> +  - code test and quality
```suggestion
  - code quality and testing
```

2018-11-15 12:11 UTC, pawzar commented on .travis.yml
> +  - stage: code test and quality
```suggestion
  - stage: code quality and testing
```

2018-11-15 16:25 UTC, teghnet approved these changes

2018-11-15 16:26 UTC, merged