SRV-35 inventory synchronization implementation
adshares/adserver pull request #186
Opened 2018-11-19 09:11 UTC by c3zi

2018-11-19 11:07 UTC, pawzar commented on app/Models/NetworkCampaign.php
>          'uuid',
I would call everything `id` & `parent_id`

2018-11-19 12:17 UTC, teghnet requested changes

2018-11-19 12:17 UTC, pawzar commented on scripts/install.sh
> +mv src ${INSTALLATION_PATH}/
duplicate

2018-11-19 12:17 UTC, pawzar commented on src/Common/Domain/Adapter/ArrayCollection.php
> +declare(strict_types=1);
formatting

2018-11-19 12:17 UTC, pawzar commented on src/Common/Domain/ValueObject/Uuid.php
> +final class Uuid
```suggestion
final class Uuid implements \Adshares\Common\Domain\Id
```

2018-11-19 12:24 UTC, teghnet commented on src/Supply/Domain/Model/Banner.php
> +    /** @var int */
int?

2018-11-19 12:51 UTC, PawelPodkalicki submitted a review, later dismissed

2018-11-19 12:51 UTC, PawelPodkalicki commented on app/Repository/Supply/NetworkCampaignRepository.php
> +        }
Lines 
```
foreach ($networkBanners as $banner) {
            $networkCampaign->banners()->save($banner);
}
```
could be swapped with
`$networkCampaign->banners()->saveMany($networkBanners);`

If accepted, remember about test `testImportWhenActivateIsSuccessful`
```
        $repository
            ->expects($this->exactly(2))
            ->method('save');
```

2018-11-19 12:51 UTC, PawelPodkalicki commented on src/Supply/Application/Service/InventoryImporter.php
> +    /*** @var DemandClient */
```suggestion
    /** @var DemandClient */
```

2018-11-19 12:51 UTC, PawelPodkalicki commented on tests/src/Supply/Application/Service/InventoryImprterTest.php
> +final class InventoryImprterTest extends TestCase
Typo in class name

2018-11-20 10:04 UTC, teghnet approved these changes

2018-11-20 10:06 UTC, merged