SRV-167 Add total to statistics
adshares/adserver pull request #352
Opened 2019-01-24 08:10 UTC by PawelPodkalicki

2019-01-24 12:21 UTC, teghnet requested changes

2019-01-24 12:21 UTC, pawzar commented on app/Http/Controllers/Manager/StatsController.php
> +        $resultData = &$result['data'];
Do not pass by reference unless REALLY necessary.

2019-01-24 12:21 UTC, pawzar commented on app/Http/Controllers/Manager/StatsController.php
> +        foreach ($resultData as &$item) {
Do array_map or something like that.

2019-01-24 17:03 UTC, teghnet approved these changes

2019-01-25 08:37 UTC, PawelPodkalicki commented
Do not merge before demo. This PR needs front-end changes
Do not merge before demo.
Do not merge before demo.
Do not merge before demo.
Do not merge before demo.
Do not merge before demo.

2019-01-28 09:03 UTC, merged