Fix banner name (for BC)
adshares/adserver pull request #601
Opened 2019-04-10 14:24 UTC by pawzar

2019-04-10 14:28 UTC, PawelPodkalicki requested changes

2019-04-10 14:28 UTC, PawelPodkalicki commented on resources/js/supply/find/find.js
> +    var tags = document.querySelectorAll(selectorClass + '[data-zone]');
https://github.com/adshares/adserver/pull/600

2019-04-10 18:05 UTC, PawelPodkalicki approved these changes

2019-04-11 05:19 UTC, c3zi approved these changes

2019-04-11 05:19 UTC, merged