SRV-362 Add global server statistics
adshares/adserver pull request #724
Opened 2019-05-31 16:38 UTC by PawelPodkalicki

2019-06-03 12:07 UTC, teghnet requested changes

2019-06-03 12:07 UTC, pawzar commented on app/Http/Controllers/Manager/StatisticsGlobalController.php
> +        $operatorFee = 0.01;
Magic number?

2019-06-03 12:12 UTC, PawelPodkalicki commented on app/Http/Controllers/Manager/StatisticsGlobalController.php
> +        $operatorFee = 0.01;
good point, Iwill fix

2019-06-04 07:17 UTC, teghnet approved these changes

2019-06-04 07:17 UTC, merged