Fetch events maximally from 7 days
adshares/adserver pull request #744
Opened 2019-06-13 10:58 UTC by c3zi

2019-06-13 11:26 UTC, PawelPodkalicki requested changes

2019-06-13 11:26 UTC, PawelPodkalicki commented on src/Supply/Application/Service/AdSelectEventExporter.php
> +        return $this->eventRepository->fetchLastPaidEventsByDate(new DateTime('-7 days'));
fetch does not match function signature paid != unpaid

2019-06-13 11:26 UTC, PawelPodkalicki commented on src/Supply/Application/Service/AdSelectEventExporter.php
> +        return $this->eventRepository->fetchLastUnPaidEventsByDate(new DateTime('-7 days'));
fetch does not match function signature paid != unpaid

2019-06-14 15:15 UTC, teghnet approved these changes

2019-06-14 15:15 UTC, merged